routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Payments\DiscountPayment;
use App\Models\Payments\Discounts\Discount;
use App\Models\Payments\Discounts\DollarDiscount;
use App\Models\Payments\Payment;
use App\Models\Registration;

Route::get('/', ['as' => 'frontend.index', 'uses' => 'FrontendController@index']);
//Route::post('/filter', ['as' => 'frontend.filter', 'uses' => 'FrontendController@filter']);
//Route::post('/process-facility-click', ['as' => 'frontend.process_facility_click', 'uses' => 'FrontendController@processFacilityClick']);


if(config('app.env') == 'local')
{
	Route::get('test', function ()
	{
		return 'nope';
	});
	Route::get('sheet', function ()
	{
		return view('frontend.sheet');
	});
	Route::get('debug', function ()
	{
		return 'debugging';
	});
}

Route::get('/login', ['as' => 'session.login', 'uses' => 'SessionController@create']);
Route::post('/login', ['as' => 'session.store', 'uses' => 'SessionController@store']);
Route::get('/logout', ['as' => 'session.destroy', 'uses' => 'SessionController@destroy']);

Route::get('/password/forgot', ['as' => 'password.reset.email.get', 'uses' => 'Auth\PasswordController@getEmail']);
Route::post('/password/forgot', ['as' => 'password.reset.email.post', 'uses' => 'Auth\PasswordController@postEmail']);
Route::get('/password/reset/{token}', ['as' => 'password.reset.get', 'uses' => 'Auth\PasswordController@getReset']);
Route::post('/password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\PasswordController@postReset']);

Route::get('/unauthorized', ['as' => 'errors.unauthorized', 'uses' => 'ErrorController@unauthorized']);


Route::group(['prefix' => '/events/'], function ()
{
	Route::get('/', ['as' => 'frontend.events.index', 'uses' => 'Frontend\EventController@index']);
	Route::get('/map', ['as' => 'frontend.events.map', 'uses' => 'Frontend\EventController@map']);
	Route::get('/{uid}', ['as' => 'frontend.events.show', 'uses' => 'Frontend\EventController@show']);
	Route::get('/{uid}/register', ['as' => 'frontend.workflows.registration.register.get', 'uses' => 'Frontend\Workflows\RegistrationWorkflowController@getRegister']);
	Route::post('/{uid}/register', ['as' => 'frontend.workflows.registration.register.post', 'uses' => 'Frontend\Workflows\RegistrationWorkflowController@postRegister']);
});

Route::group(['prefix' => '/registrations/'], function ()
{
	Route::get('/{uid}/{passcode}', ['as' => 'frontend.registrations.show', 'uses' => 'Frontend\RegistrationController@show']);
	Route::get('/{uid}/invoice/{passcode}', ['as' => 'frontend.registrations.invoice', 'uses' => 'Frontend\RegistrationController@invoice']);
	Route::get('/{uid}/pay/{passcode}', ['as' => 'frontend.workflows.payment.get', 'uses' => 'Frontend\Workflows\PaymentWorkflowController@getProcessPayment']);
	Route::post('/{uid}/pay/{passcode}', ['as' => 'frontend.workflows.payment.post', 'uses' => 'Frontend\Workflows\PaymentWorkflowController@postProcessPayment']);
	Route::post('/pay/apply-promo-code', ['as' => 'frontend.workflows.payment.apply_discount', 'uses' => 'Frontend\Workflows\PaymentWorkflowController@applyDiscount']);
});

Route::group(['prefix' => '/recaptcha/'], function ()
{
	Route::post('/verify', ['as' => 'frontend.recaptcha.verify', 'uses' => 'Frontend\RecaptchaController@verify']);
	Route::get('/fail', ['as' => 'frontend.recaptcha.fail', 'uses' => 'Frontend\RecaptchaController@fail']);
});


Route::group(['prefix' => '/manage/', 'namespace' => 'Backend'], function ()
{
	Route::get('/', ['as' => 'backend.dashboard.index', 'uses' => 'DashboardController@index']);
//	Route::get('/', ['as' => 'backend.dashboard.index', 'uses' => '\App\Http\Controllers\FrontendController@interactiveMap']);

	Route::group(['prefix' => '/my-account/'], function ()
	{
		Route::get('/', ['as' => 'backend.my_account.show', 'uses' => 'MyAccountController@show']);
		Route::get('/edit', ['as' => 'backend.my_account.edit.get', 'uses' => 'MyAccountController@getEdit']);
		Route::post('/edit', ['as' => 'backend.my_account.edit.post', 'uses' => 'MyAccountController@postEdit']);
		Route::get('/change-password', ['as' => 'backend.my_account.change_password.get', 'uses' => 'MyAccountController@getChangePassword']);
		Route::post('/change-password', ['as' => 'backend.my_account.change_password.post', 'uses' => 'MyAccountController@postChangePassword']);
	});

	Route::group(['prefix' => '/addresses/'], function ()
	{
		Route::get('/', ['as' => 'backend.addresses.index', 'uses' => 'AddressController@index']);
		Route::get('/{id}', ['as' => 'backend.addresses.show', 'uses' => 'AddressController@show']);
		Route::get('/{id}/edit', ['as' => 'backend.addresses.edit.get', 'uses' => 'AddressController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.addresses.edit.post', 'uses' => 'AddressController@postEdit']);
		Route::get('/{id}/destroy', ['as' => 'backend.addresses.destroy', 'uses' => 'AddressController@destroy']);
	});

	Route::group(['prefix' => '/attendees/'], function ()
	{
		Route::get('/', ['as' => 'backend.attendees.index', 'uses' => 'AttendeeController@index']);
		Route::get('/{id}', ['as' => 'backend.attendees.show', 'uses' => 'AttendeeController@show']);
		Route::get('/{id}/edit', ['as' => 'backend.attendees.edit.get', 'uses' => 'AttendeeController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.attendees.edit.post', 'uses' => 'AttendeeController@postEdit']);
		Route::get('/{id}/destroy', ['as' => 'backend.attendees.destroy', 'uses' => 'AttendeeController@destroy']);
	});

	Route::group(['prefix' => '/courses/'], function ()
	{
		Route::get('/', ['as' => 'backend.courses.index', 'uses' => 'CourseController@index']);
		Route::get('/create', ['as' => 'backend.courses.create.get', 'uses' => 'CourseController@getCreate']);
		Route::post('/create', ['as' => 'backend.courses.create.post', 'uses' => 'CourseController@postCreate']);
		Route::get('/{id}', ['as' => 'backend.courses.show', 'uses' => 'CourseController@show']);
		Route::get('/{id}/edit', ['as' => 'backend.courses.edit.get', 'uses' => 'CourseController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.courses.edit.post', 'uses' => 'CourseController@postEdit']);
		Route::get('/{id}/destroy', ['as' => 'backend.courses.destroy', 'uses' => 'CourseController@destroy']);
	});

	Route::group(['prefix' => '/discounts/'], function ()
	{
		Route::get('/', ['as' => 'backend.discounts.index', 'uses' => 'DiscountController@index']);
		Route::get('/active', ['as' => 'backend.discounts.active', 'uses' => 'DiscountController@active']);
		Route::get('/inactive', ['as' => 'backend.discounts.inactive', 'uses' => 'DiscountController@inactive']);
		Route::get('/create', ['as' => 'backend.discounts.create.get', 'uses' => 'DiscountController@getCreate']);
		Route::post('/create', ['as' => 'backend.discounts.create.post', 'uses' => 'DiscountController@postCreate']);
		Route::get('/{id}', ['as' => 'backend.discounts.show', 'uses' => 'DiscountController@show']);
		Route::get('/{id}/edit', ['as' => 'backend.discounts.edit.get', 'uses' => 'DiscountController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.discounts.edit.post', 'uses' => 'DiscountController@postEdit']);
		Route::get('/{id}/destroy', ['as' => 'backend.discounts.destroy', 'uses' => 'DiscountController@destroy']);
	});

	Route::group(['prefix' => '/events/'], function ()
	{
		Route::get('/', ['as' => 'backend.events.index', 'uses' => 'EventController@index']);
		Route::get('/create', ['as' => 'backend.events.create.get', 'uses' => 'EventController@getCreate']);
		Route::post('/create', ['as' => 'backend.events.create.post', 'uses' => 'EventController@postCreate']);
		Route::get('/{id}', ['as' => 'backend.events.show', 'uses' => 'EventController@show']);
		Route::get('/{id}/audits', ['as' => 'backend.events.audits', 'uses' => 'EventController@audits']);
		Route::get('/{id}/attendees', ['as' => 'backend.events.attendees', 'uses' => 'AttendeeController@indexByEvent']);
		Route::get('/{id}/tickets', ['as' => 'backend.events.tickets', 'uses' => 'TicketController@indexByEvent']);
		Route::get('/{id}/venues', ['as' => 'backend.events.venues', 'uses' => 'VenueController@indexByEvent']);
		Route::get('/{id}/edit', ['as' => 'backend.events.edit.get', 'uses' => 'EventController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.events.edit.post', 'uses' => 'EventController@postEdit']);
		Route::get('/{id}/mark-settled', ['as' => 'backend.events.mark_settled', 'uses' => 'EventController@markSettled']);
		Route::get('/{id}/mark-unsettled', ['as' => 'backend.events.mark_unsettled', 'uses' => 'EventController@markUnsettled']);
		Route::get('/{id}/destroy', ['as' => 'backend.events.destroy', 'uses' => 'EventController@destroy']);
	});

	Route::group(['prefix' => '/lodgings/'], function ()
	{
		Route::get('/', ['as' => 'backend.lodgings.index', 'uses' => 'LodgingController@index']);
		Route::get('/create', ['as' => 'backend.lodgings.create.get', 'uses' => 'LodgingController@getCreate']);
		Route::post('/create', ['as' => 'backend.lodgings.create.post', 'uses' => 'LodgingController@postCreate']);
		Route::get('/{id}', ['as' => 'backend.lodgings.show', 'uses' => 'LodgingController@show']);
		Route::get('/{id}/edit', ['as' => 'backend.lodgings.edit.get', 'uses' => 'LodgingController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.lodgings.edit.post', 'uses' => 'LodgingController@postEdit']);
		Route::get('/{id}/generate-embedded-map', ['as' => 'backend.lodgings.generate_embedded_map', 'uses' => 'LodgingController@generateEmbeddedMap']);

app/Models/Ticket.php
<?php namespace App\Models;

use App\Traits\HasNotes;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class Ticket extends BaseModel implements AuditableContract
{
	use AuditableTrait, HasNotes;

	protected $table    = 'tickets';
	protected $fillable = [
		'uid',
		'event_id',
		'registration_id',
		'attendee_id',
		'price_in_cents',
	];

	public static function getAttributeMap()
	{
		return [
			'price_in_cents' => 'integer',
		];
	}


	/* ELOQUENT */
	public function event()
	{
		return $this->belongsTo(Event::class, 'event_id');
	}

	public function registration()
	{
		return $this->belongsTo(Registration::class, 'registration_id');
	}

	public function attendee()
	{
		return $this->belongsTo(Attendee::class, 'attendee_id');
	}


	/* QUERIES */


	/* GETTERS / SETTERS */


	/* PRESENTATION */
	public function getPriceInDollarsAttribute()
	{
		return $this->price_in_cents / 100;
	}

	public function display()
	{
		return $this->uid;
	}

	public function backendDisplayRoutes()
	{
		return [
			'show' => 'backend.tickets.show'
		];
	}
}

app/Http/Controllers/Api/EventController.php
<?php namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Event;
use Input;

class EventController extends Controller
{
	public function upcomingEvents()
	{
		$count = Input::get('count', 10);
		$_events = Event::query()
					   ->published()
					   ->upcoming()
					   ->orderBy('start_at', 'asc')
					   ->take($count)
					   ->get();

		$events = [];
		foreach($_events as $_event)
		{
			$event = [];
			$event['display'] = $_event->start_at->format('M j'). ': ' . $_event->course->name . ' (' . $_event->venue->address->city . ', ' . $_event->venue->address->state->short_name . ')';
			$event['url'] = route('frontend.events.show', $_event->uid);
			$events[] = $event;
		}

		return json_encode([
			'success' => true,
			'events'  => $events
		]);
	}
}

app/Http/Controllers/Frontend/EventController.php
<?php namespace App\Http\Controllers\Frontend;

use App\Helpers\TimezoneHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Events\DestroyEventRequest;
use App\Http\Requests\Backend\Events\PostCreateEventRequest;
use App\Http\Requests\Backend\Events\PostEditEventRequest;
use App\Http\Requests\Backend\Registrations\PostRegisterRequest;
use App\Models\Address;
use App\Models\Attendee;
use App\Models\Course;
use App\Models\DepartmentSize;
use App\Models\Event;
use App\Models\Registration;
use App\Models\State;
use App\Models\Ticket;
use App\Models\Venue;
use Illuminate\Support\Facades\Redirect;
use Input;
use Setting;

class EventController extends Controller
{
	public function index()
	{
		$events_query = Event::query();
		if($course_uid = Input::get('course', false))
		{
			$course = Course::where('uid', $course_uid)->get()->first();
			if($course)
			{
				$events_query->where('course_id', $course->id);
			}
		}
		if($state = Input::get('state', false))
		{
			$events_query->where('state', $state);
		}
		$events = $events_query
			->where('start_at', '>=', \Carbon::today('UTC'))
			->orderBy('start_at', 'asc')
			->get();

		$vars = compact('events');

		return view('frontend.events.index', $vars);
	}

	public function map()
	{
		list($start_at, $end_at) = $this->getDateRange([
			'start_default' => \Carbon::today()->subMonth(),
			'end_default'   => \Carbon::today()->addMonth(),
		]);
		$events_query = Event::query()
							 ->where('start_at', '>=', \Carbon::today('UTC'))
							 ->whereBetween('start_at', [$start_at, $end_at]);
		if($course_uid = Input::get('course', false))
		{
			$course = Course::where('uid', $course_uid)->get()->first();
			if($course)
			{
				$events_query->where('course_id', $course->id);
			}
		}
		if($state = Input::get('state', false))
		{
			$events_query->where('state', $state);
		}
		$events = $events_query
			->orderBy('start_at', 'asc')
			->get();

		$markers = [];
		foreach($events as $event)
		{
			$marker = [
				'title'     => htmlentities($event->displayClass(), ENT_QUOTES),
				'course'    => htmlentities($event->course->display(), ENT_QUOTES),
				'link'      => route('frontend.events.show', [$event->uid]),
				'latitude'  => $event->venue->latitude,
				'longitude' => $event->venue->longitude,
				'start'     => $event->start_at->format('m/d/Y'),
				'location'  => htmlentities($event->venue->address->city . ', ' . $event->venue->address->state->short_name, ENT_QUOTES),
				'venue'     => htmlentities($event->venue->name, ENT_QUOTES)
			];

			$markers[] = $marker;
		}

		$vars = compact(
			'markers',
			'start_at',
			'end_at'
		);

		return view('frontend.events.map', $vars);
	}

	public function show($uid)
	{
		$event = Event::where('uid', $uid)->get()->first();
		if(!$event)
		{
			abort(404);

			return false;
		}

		$vars = compact('event');

		return view('frontend.events.show', $vars);
	}
}

resources/views/backend/events/partials/analytics.blade.php
<strong>Tickets:</strong> {{ number_format($event->tickets()->count(), 0) }}<br />
<strong>Registrations:</strong> {{ number_format($event->registrations()->count(), 0) }}<br />
<strong>Payments:</strong> {{ number_format($event->getPaymentsQuery()->count(), 0) }}<br />
<strong>Balance:</strong> ${{ number_format($event->getPaymentsQuery()->sum('amount_in_cents') / 100, 2) }} / ${{ number_format($event->tickets()->sum('price_in_cents') / 100, 2) }}<br />
@if($event->tickets()->count() > 0)
    <strong>Percent Paid:</strong> {{ number_format(($event->getPaymentsQuery()->sum('amount_in_cents') / $event->tickets()->sum('price_in_cents')) * 100, 2) }}%<br />
@else
    <strong>Percent Paid:</strong> 0%<br />
@endif
@if($event->revenue_goal)
    <strong>Revenue Goal:</strong> ${{ number_format($event->tickets()->sum('price_in_cents') / 100, 2) }} / ${{ number_format($event->revenue_goal / 100, 2) }} ({{ number_format( ($event->tickets()->sum('price_in_cents') / $event->revenue_goal) * 100, 2) }}% Fulfilled)<br />
@else
    <strong>Revenue Goal:</strong> N/A<br />
@endif
<strong>Credit Payments:</strong> ${{ number_format($event->getPaymentsQuery()->creditCardPayments()->sum('amount_in_cents') / 100, 2) }} ({{ number_format(($event->getPaymentsQuery()->creditCardPayments()->count()), 0) }} Payments)<br />
<strong>Check Payments:</strong> ${{ number_format($event->getPaymentsQuery()->checkPayments()->sum('amount_in_cents') / 100, 2) }} ({{ number_format(($event->getPaymentsQuery()->checkPayments()->count()), 0) }} Payments)<br />
<strong>Discount Payments:</strong> ${{ number_format($event->getPaymentsQuery()->discountPayments()->sum('amount_in_cents') / 100, 2) }} ({{ number_format(($event->getPaymentsQuery()->discountPayments()->count()), 0) }} Payments)<br />

<style>
    .chart-container {
        display: flex;
        flex-wrap: wrap;
    }
    .chart-container > canvas {
        width: 50%;
    }
</style>
<div class="chart-container">
    <canvas id="payments_chart" width="400" height="225"></canvas>
    @if($event->revenue_goal)
        <canvas id="goal_chart" width="400" height="225"></canvas>
    @endif
    <canvas id="timeline_chart" width="400" height="225"></canvas>
</div>

<script>
    $(document).ready(function()
    {
        var payments_chart = new Chart(document.getElementById("payments_chart"), {
            type: 'pie',
            data: {
                labels: ["Credit", "Check", "Discount"],
                datasets: [
                    {
                        label: 'Dollars',
                        backgroundColor: ['green', 'blue', 'red'],
                        data: [
                            '{{ number_format($event->getPaymentsQuery()->creditCardPayments()->sum('amount_in_cents') / 100, 2) }}',
                            '{{ number_format($event->getPaymentsQuery()->checkPayments()->sum('amount_in_cents') / 100, 2) }}',
                            '{{ number_format($event->getPaymentsQuery()->discountPayments()->sum('amount_in_cents') / 100, 2) }}',
                        ]
                    },
                    {
                        label: 'Count',
                        backgroundColor: ['green', 'blue', 'red'],
                        data: [
                            '{{ number_format($event->getPaymentsQuery()->creditCardPayments()->count(), 0) }}',
                            '{{ number_format($event->getPaymentsQuery()->checkPayments()->count(), 0) }}',
                            '{{ number_format($event->getPaymentsQuery()->discountPayments()->count(), 0) }}',
                        ]
                    }
                ]
            },
            options: {
                title: {
                    display: true,
                    text: 'Payments'
                }
            }
        });
        @if($event->revenue_goal)
        var goal_chart = new Chart(document.getElementById("goal_chart"), {
            type: 'pie',
            data: {
                labels: ["Paid", "Promised", "Goal"],
                datasets: [
                    {
                        label: 'Amount',
                        backgroundColor: ['green', 'blue', 'red'],
                        data: [
                            '{{ $event->getPaymentsQuery()->sum('amount_in_cents') / 100 }}',
                            '{{ ($event->tickets()->sum('price_in_cents') - $event->getPaymentsQuery()->sum('amount_in_cents')) / 100 }}',
                            '{{ ($event->revenue_goal - $event->tickets()->sum('price_in_cents')) / 100 }}'
                        ]
                    },
                    {
                        label: 'Percent',
                        backgroundColor: ['green', 'blue', 'red'],
                        data: [
                            '{{ $event->getPaymentsQuery()->sum('amount_in_cents') / $event->revenue_goal }}',
                            '{{ ($event->tickets()->sum('price_in_cents') - $event->getPaymentsQuery()->sum('amount_in_cents')) / $event->revenue_goal }}',
                            '{{ ($event->revenue_goal - $event->tickets()->sum('price_in_cents')) / $event->revenue_goal }}'
                        ]
                    }
                ]
            },
            options: {
                title: {
                    display: true,
                    text: 'Revenue Goal'
                }
            }
        });
        @endif
        var timeline_chart = new Chart(document.getElementById("timeline_chart"), {
            type: 'line',
            data: {
                fill: false,
                labels: ['{!! implode("','", $timeline_chart_labels) !!}'],
                datasets: [
                    {
                        label: 'Registrations',
                        fill: false,
                        borderColor: ['blue'],
                        data: [{{ implode(',', $timeline_chart_data['registrations']) }}]
                    },
                    {
                        label: 'Payments',
                        fill: false,
                        borderColor: ['green'],
                        data: [{{ implode(',', $timeline_chart_data['payments']) }}]
                    }
                ]
            },
            options: {
                title: {
                    display: true,
                    text: 'Registrations'
                }
            }
        });
    });
</script>

resources/views/backend/events/partials/snapshot.blade.php
<p>
    <strong>ID:</strong> {{ $event->id }}<br />
    <strong>UID:</strong> {{ $event->uid }}<br />
    <strong>Name:</strong> {{ $event->name }}<br />
    <strong>Tagline:</strong> {{ $event->tagline }}<br />
    <strong>Description:</strong> {{ $event->description }}<br />
</p>

resources/views/backend/events/partials/table.blade.php
<?php $table_id = isset($table_id) ? $table_id : 'event_table'; ?>

<table id="{{ $table_id }}" class="datatable">
    <thead>
    <tr>
        <th>ID</th>
        <th>UID</th>
        <th>Venue</th>
        <th>Course</th>
        <th>Timezone</th>
        <th>Start</th>
        <th>End</th>
        <th>Deadline</th>
        <th>Limit</th>
        <th>Price</th>
        <th>Goal</th>
        <th>Published?</th>
        <th>Finalized?</th>
        <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    @foreach($events as $event)
        <tr>
            <td>{!! link_to_route('backend.events.show', $event->id, [$event->id]) !!}</td>
            <td>{!! link_to_route('backend.events.show', $event->uid, [$event->id]) !!}</td>
            <td>{!! link_to_route('backend.venues.show', $event->venue->display(), [$event->venue_id]) !!}</td>
            <td>{!! link_to_route('backend.courses.show', $event->course->display(), [$event->course_id]) !!}</td>
            <td>{{ $event->timezone }}</td>
            <td>{!! Helper::displayCalendarDate($event->start_at) !!}</td>
            <td>{!! Helper::displayCalendarDate($event->end_at) !!}</td>
            <td>{!! Helper::displayCalendarDate($event->deadline_at) !!}</td>
            <td class="align-right">{{ number_format($event->ticket_limit, 0) }}</td>
            <td class="align-right">${{ number_format($event->price_in_dollars, 2) }}</td>
            <td class="align-right">${{ number_format($event->revenue_goal, 2) }}</td>
            <td>{{ $event->published_status }}</td>
            <td>{{ $event->is_finalized ? 'Yes' : 'No' }}</td>
            <td class="icon-td">
                {!! Helper::icon_to_route('backend.events.show', 'fa-eye', [$event->id], ['title' => 'View Event']) !!}
                {!! Helper::icon_to_route('backend.events.edit.get', 'fa-pencil', [$event->id], ['title' => 'Edit Event']) !!}
                {!! Helper::icon_to_route('backend.events.destroy', 'fa-ban', [$event->id], ['title' => 'Delete Event']) !!}
            </td>
        </tr>
    @endforeach
    </tbody>

</table>

<script>
    $(document).ready(function()
    {
        var hidden_columns;
        @include('includes.js.hidden_columns', ['default_hidden_columns' => ['ID' => 1,'Deadline' => 1]])

        var table_id = '{{ $table_id }}';
        datatables[table_id] = init_datatable_i(table_id, {hiddenColumns: hidden_columns});

        @if(isset($has_filtering) && $has_filtering)
        $('.filter').change(function()
        {
            datatables[table_id].draw();
        });
        @endif
    });
</script>

resources/views/backend/events/partials/table_rows.blade.php
@foreach($events as $event)
    <tr>
        <td>{!! link_to_route('backend.events.show', $event->id, [$event->id]) !!}</td>
        <td>{!! link_to_route('backend.events.show', $event->uid, [$event->id]) !!}</td>
        <td>{!! link_to_route('backend.venues.show', $event->venue->display(), [$event->venue_id]) !!}</td>
        <td>{!! link_to_route('backend.courses.show', $event->course->display(), [$event->course_id]) !!}</td>
        <td>{{ $event->timezone }}</td>
        <td>{!! Helper::displayCalendarDate($event->start_at) !!}</td>
        <td>{!! Helper::displayCalendarDate($event->end_at) !!}</td>
        <td>{!! Helper::displayCalendarDate($event->deadline_at) !!}</td>
        <td class="align-right">{{ number_format($event->ticket_limit, 0) }}</td>
        <td class="align-right">${{ number_format($event->price_in_dollars, 2) }}</td>
        <td class="align-right">${{ number_format($event->revenue_goal, 2) }}</td>
        <td>{{ $event->published_status }}</td>
        <td>{{ $event->is_finalized ? 'Yes' : 'No' }}</td>
        <td>{{ $event->notes }}</td>
        <td class="icon-td">
            {!! Helper::icon_to_route('backend.events.show', 'fa-eye', [$event->id], ['title' => 'View Event']) !!}
            {!! Helper::icon_to_route('backend.events.edit.get', 'fa-pencil', [$event->id], ['title' => 'Edit Event']) !!}
            {!! Helper::icon_to_route('backend.events.destroy', 'fa-ban', [$event->id], ['title' => 'Delete Event']) !!}
        </td>
    </tr>
@endforeach