routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Payments\DiscountPayment;
use App\Models\Payments\Discounts\Discount;
use App\Models\Payments\Discounts\DollarDiscount;
use App\Models\Payments\Payment;
use App\Models\Registration;

Route::get('/', ['as' => 'frontend.index', 'uses' => 'FrontendController@index']);
//Route::post('/filter', ['as' => 'frontend.filter', 'uses' => 'FrontendController@filter']);
//Route::post('/process-facility-click', ['as' => 'frontend.process_facility_click', 'uses' => 'FrontendController@processFacilityClick']);


if(config('app.env') == 'local')
{
	Route::get('test', function ()
	{
		return 'nope';
	});
	Route::get('sheet', function ()
	{
		return view('frontend.sheet');
	});
	Route::get('debug', function ()
	{
		return 'debugging';
	});
}

Route::get('/login', ['as' => 'session.login', 'uses' => 'SessionController@create']);
Route::post('/login', ['as' => 'session.store', 'uses' => 'SessionController@store']);
Route::get('/logout', ['as' => 'session.destroy', 'uses' => 'SessionController@destroy']);

Route::get('/password/forgot', ['as' => 'password.reset.email.get', 'uses' => 'Auth\PasswordController@getEmail']);
Route::post('/password/forgot', ['as' => 'password.reset.email.post', 'uses' => 'Auth\PasswordController@postEmail']);
Route::get('/password/reset/{token}', ['as' => 'password.reset.get', 'uses' => 'Auth\PasswordController@getReset']);
Route::post('/password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\PasswordController@postReset']);

Route::get('/unauthorized', ['as' => 'errors.unauthorized', 'uses' => 'ErrorController@unauthorized']);


Route::group(['prefix' => '/events/'], function ()
{
	Route::get('/', ['as' => 'frontend.events.index', 'uses' => 'Frontend\EventController@index']);
	Route::get('/map', ['as' => 'frontend.events.map', 'uses' => 'Frontend\EventController@map']);
	Route::get('/{uid}', ['as' => 'frontend.events.show', 'uses' => 'Frontend\EventController@show']);
	Route::get('/{uid}/register', ['as' => 'frontend.workflows.registration.register.get', 'uses' => 'Frontend\Workflows\RegistrationWorkflowController@getRegister']);
	Route::post('/{uid}/register', ['as' => 'frontend.workflows.registration.register.post', 'uses' => 'Frontend\Workflows\RegistrationWorkflowController@postRegister']);
});

Route::group(['prefix' => '/registrations/'], function ()
{
	Route::get('/{uid}/{passcode}', ['as' => 'frontend.registrations.show', 'uses' => 'Frontend\RegistrationController@show']);
	Route::get('/{uid}/invoice/{passcode}', ['as' => 'frontend.registrations.invoice', 'uses' => 'Frontend\RegistrationController@invoice']);
	Route::get('/{uid}/pay/{passcode}', ['as' => 'frontend.workflows.payment.get', 'uses' => 'Frontend\Workflows\PaymentWorkflowController@getProcessPayment']);
	Route::post('/{uid}/pay/{passcode}', ['as' => 'frontend.workflows.payment.post', 'uses' => 'Frontend\Workflows\PaymentWorkflowController@postProcessPayment']);
	Route::post('/pay/apply-promo-code', ['as' => 'frontend.workflows.payment.apply_discount', 'uses' => 'Frontend\Workflows\PaymentWorkflowController@applyDiscount']);
});

Route::group(['prefix' => '/recaptcha/'], function ()
{
	Route::post('/verify', ['as' => 'frontend.recaptcha.verify', 'uses' => 'Frontend\RecaptchaController@verify']);
	Route::get('/fail', ['as' => 'frontend.recaptcha.fail', 'uses' => 'Frontend\RecaptchaController@fail']);
});


Route::group(['prefix' => '/manage/', 'namespace' => 'Backend'], function ()
{
	Route::get('/', ['as' => 'backend.dashboard.index', 'uses' => 'DashboardController@index']);
//	Route::get('/', ['as' => 'backend.dashboard.index', 'uses' => '\App\Http\Controllers\FrontendController@interactiveMap']);

	Route::group(['prefix' => '/my-account/'], function ()
	{
		Route::get('/', ['as' => 'backend.my_account.show', 'uses' => 'MyAccountController@show']);
		Route::get('/edit', ['as' => 'backend.my_account.edit.get', 'uses' => 'MyAccountController@getEdit']);
		Route::post('/edit', ['as' => 'backend.my_account.edit.post', 'uses' => 'MyAccountController@postEdit']);
		Route::get('/change-password', ['as' => 'backend.my_account.change_password.get', 'uses' => 'MyAccountController@getChangePassword']);
		Route::post('/change-password', ['as' => 'backend.my_account.change_password.post', 'uses' => 'MyAccountController@postChangePassword']);
	});

	Route::group(['prefix' => '/addresses/'], function ()
	{
		Route::get('/', ['as' => 'backend.addresses.index', 'uses' => 'AddressController@index']);
		Route::get('/{id}', ['as' => 'backend.addresses.show', 'uses' => 'AddressController@show']);
		Route::get('/{id}/edit', ['as' => 'backend.addresses.edit.get', 'uses' => 'AddressController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.addresses.edit.post', 'uses' => 'AddressController@postEdit']);
		Route::get('/{id}/destroy', ['as' => 'backend.addresses.destroy', 'uses' => 'AddressController@destroy']);
	});

	Route::group(['prefix' => '/attendees/'], function ()
	{
		Route::get('/', ['as' => 'backend.attendees.index', 'uses' => 'AttendeeController@index']);
		Route::get('/{id}', ['as' => 'backend.attendees.show', 'uses' => 'AttendeeController@show']);
		Route::get('/{id}/edit', ['as' => 'backend.attendees.edit.get', 'uses' => 'AttendeeController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.attendees.edit.post', 'uses' => 'AttendeeController@postEdit']);
		Route::get('/{id}/destroy', ['as' => 'backend.attendees.destroy', 'uses' => 'AttendeeController@destroy']);
	});

	Route::group(['prefix' => '/courses/'], function ()
	{
		Route::get('/', ['as' => 'backend.courses.index', 'uses' => 'CourseController@index']);
		Route::get('/create', ['as' => 'backend.courses.create.get', 'uses' => 'CourseController@getCreate']);
		Route::post('/create', ['as' => 'backend.courses.create.post', 'uses' => 'CourseController@postCreate']);
		Route::get('/{id}', ['as' => 'backend.courses.show', 'uses' => 'CourseController@show']);
		Route::get('/{id}/edit', ['as' => 'backend.courses.edit.get', 'uses' => 'CourseController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.courses.edit.post', 'uses' => 'CourseController@postEdit']);
		Route::get('/{id}/destroy', ['as' => 'backend.courses.destroy', 'uses' => 'CourseController@destroy']);
	});

	Route::group(['prefix' => '/discounts/'], function ()
	{
		Route::get('/', ['as' => 'backend.discounts.index', 'uses' => 'DiscountController@index']);
		Route::get('/active', ['as' => 'backend.discounts.active', 'uses' => 'DiscountController@active']);
		Route::get('/inactive', ['as' => 'backend.discounts.inactive', 'uses' => 'DiscountController@inactive']);
		Route::get('/create', ['as' => 'backend.discounts.create.get', 'uses' => 'DiscountController@getCreate']);
		Route::post('/create', ['as' => 'backend.discounts.create.post', 'uses' => 'DiscountController@postCreate']);
		Route::get('/{id}', ['as' => 'backend.discounts.show', 'uses' => 'DiscountController@show']);
		Route::get('/{id}/edit', ['as' => 'backend.discounts.edit.get', 'uses' => 'DiscountController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.discounts.edit.post', 'uses' => 'DiscountController@postEdit']);
		Route::get('/{id}/destroy', ['as' => 'backend.discounts.destroy', 'uses' => 'DiscountController@destroy']);
	});

	Route::group(['prefix' => '/events/'], function ()
	{
		Route::get('/', ['as' => 'backend.events.index', 'uses' => 'EventController@index']);
		Route::get('/create', ['as' => 'backend.events.create.get', 'uses' => 'EventController@getCreate']);
		Route::post('/create', ['as' => 'backend.events.create.post', 'uses' => 'EventController@postCreate']);
		Route::get('/{id}', ['as' => 'backend.events.show', 'uses' => 'EventController@show']);
		Route::get('/{id}/audits', ['as' => 'backend.events.audits', 'uses' => 'EventController@audits']);
		Route::get('/{id}/attendees', ['as' => 'backend.events.attendees', 'uses' => 'AttendeeController@indexByEvent']);
		Route::get('/{id}/tickets', ['as' => 'backend.events.tickets', 'uses' => 'TicketController@indexByEvent']);
		Route::get('/{id}/venues', ['as' => 'backend.events.venues', 'uses' => 'VenueController@indexByEvent']);
		Route::get('/{id}/edit', ['as' => 'backend.events.edit.get', 'uses' => 'EventController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.events.edit.post', 'uses' => 'EventController@postEdit']);
		Route::get('/{id}/mark-settled', ['as' => 'backend.events.mark_settled', 'uses' => 'EventController@markSettled']);
		Route::get('/{id}/mark-unsettled', ['as' => 'backend.events.mark_unsettled', 'uses' => 'EventController@markUnsettled']);
		Route::get('/{id}/destroy', ['as' => 'backend.events.destroy', 'uses' => 'EventController@destroy']);
	});

	Route::group(['prefix' => '/lodgings/'], function ()
	{
		Route::get('/', ['as' => 'backend.lodgings.index', 'uses' => 'LodgingController@index']);
		Route::get('/create', ['as' => 'backend.lodgings.create.get', 'uses' => 'LodgingController@getCreate']);
		Route::post('/create', ['as' => 'backend.lodgings.create.post', 'uses' => 'LodgingController@postCreate']);
		Route::get('/{id}', ['as' => 'backend.lodgings.show', 'uses' => 'LodgingController@show']);
		Route::get('/{id}/edit', ['as' => 'backend.lodgings.edit.get', 'uses' => 'LodgingController@getEdit']);
		Route::post('/{id}/edit', ['as' => 'backend.lodgings.edit.post', 'uses' => 'LodgingController@postEdit']);
		Route::get('/{id}/generate-embedded-map', ['as' => 'backend.lodgings.generate_embedded_map', 'uses' => 'LodgingController@generateEmbeddedMap']);

app/Models/Course.php
<?php namespace App\Models;

use App\Models\Payments\Payment;
use App\Traits\HasNotes;
use Helper;

class Course extends BaseModel
{
	use HasNotes;

	protected $table    = 'courses';
	protected $fillable = [
		'uid',
		'name',
		'short_name',
		'description',
//		'notes',
	];

	public static function getAttributeMap()
	{
		return [
			'name'        => 'string-escaped',
			'short_name'  => 'string-escaped',
			'description' => 'text-escaped',
//			'notes'       => 'text-escaped',
		];
	}


	/* ELOQUENT */
	public function events()
	{
		return $this->hasMany(Event::class, 'course_id');
	}

	public function getTicketsQuery()
	{
		$event_ids = $this->events()->pluck('id')->all();

		return Ticket::query()->whereIn('event_id', $event_ids);
	}

	public function getTickets()
	{
		return $this->getTicketsQuery()->get();
	}

	public function getRegistrationsQuery()
	{
		$event_ids = $this->events()->pluck('id')->all();

		return Registration::query()->whereIn('event_id', $event_ids);
	}

	public function getRegistrations()
	{
		return $this->getRegistrationsQuery()->get();
	}

	public function getPaymentsQuery()
	{
		$registration_ids = $this->getRegistrationsQuery()->pluck('id')->all();

		return Payment::query()->whereIn('registration_id', $registration_ids);
	}

	public function getPayments()
	{
		return $this->getPaymentsQuery()->get();
	}


	/* PRESENTATION */
	public function getShortName()
	{
		return $this->short_name ?: Helper::getCapitalLetters($this->name);
	}

	public function display()
	{
		return $this->name;
	}


	/* ANALYTICS*/
}

resources/views/backend/_templates/executives/header.blade.php
<div class="top">
    <h2 class="page-title">@yield('page-title')</h2>
    <ul class="controls">
        @if (Auth::guest())
            <li><a href="{{ url('/login') }}">Login</a></li>
        @else
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Options <span class="caret"></span></a>
                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                    <li><a href="{{ route('backend.my_account.show') }}">My Account</a></li>
                    <li><a href="{{ route('session.destroy') }}">Logout</a></li>
                </ul>
            </li>
        @endif
    </ul>
</div>
@if (View::hasSection('breadcrumbs'))
    <div class="bottom">
        <div class="breadcrumb-wrapper">
            <span class="title">You are here:</span>
            @yield('breadcrumbs')
        </div>
    </div>
@endif

resources/views/backend/_templates/executives/sidebar.blade.php
{{--<div class="shutter"></div>--}}
<div class="head">
    <div class="logo">
        <a class="large" href="{{ route('backend.dashboard.index') }}">
            <img style="width: 176px; height: 75px;" src="{{ asset(Setting::get('sidebar-logo-large', 'images/logos/sidebar.svg')) }}" />
            <span class="title">{{ Setting::get('site-title', 'Admin Center') }}</span>
        </a>
        <a class="small" href="{{ route('backend.dashboard.index') }}">
            <img src="{{ asset(Setting::get('sidebar-logo-small', 'images/logos/sidebar-small.svg')) }}" />
            <span class="title">{{ Setting::get('site-title', 'Admin Center') }}</span>
        </a>
    </div>
    <div class="user">
        <img class="icon" src="{{ Auth::user()->getGravatarImageUrl() }}" />
        <div class="details">
            <span class="username">{{ Auth::user()->username }}</span>
            <span class="role">{{ Auth::user()->getRole()->display() }}</span>
        </div>
    </div>
</div>
<ul class="navigation sidebar-nav">
    <li class="heading">Manage</li>
    <li><a href="{{ route('backend.dashboard.index') }}"><i class="fa fa-dashboard icon"></i><span>Dashboard</span></a>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-building icon"></i><span>Addresses<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Addresses</li>
            <li><a href="{{ route('backend.addresses.index') }}">View All</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-users icon"></i><span>Attendees<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Attendees</li>
            <li><a href="{{ route('backend.attendees.index') }}">View All</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-tag icon"></i><span>Discounts<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Discounts</li>
            <li><a href="{{ route('backend.discounts.index') }}">View All</a></li>
            <li><a href="{{ route('backend.discounts.active') }}">View Active</a></li>
            <li><a href="{{ route('backend.discounts.inactive') }}">View Inactive</a></li>
            <li><a href="{{ route('backend.discounts.create.get') }}">Create New</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-graduation-cap icon"></i><span>Courses<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Courses</li>
            <li><a href="{{ route('backend.courses.index') }}">View All</a></li>
            <li><a href="{{ route('backend.courses.create.get') }}">Create New</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-calendar icon"></i><span>Events<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Events</li>
            <li><a href="{{ route('backend.events.index') }}">View All</a></li>
            <li><a href="{{ route('backend.events.create.get') }}">Create New</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-bed icon"></i><span>Lodgings<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Lodgings</li>
            <li><a href="{{ route('backend.lodgings.index') }}">View All</a></li>
            <li><a href="{{ route('backend.lodgings.create.get') }}">Create New</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-file-text icon"></i><span>Registrations<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Registrations</li>
            <li><a href="{{ route('backend.registrations.index') }}">View All</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-ticket icon"></i><span>Tickets<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Tickets</li>
            <li><a href="{{ route('backend.tickets.index') }}">View All</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-bank icon"></i><span>Venues<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Venues</li>
            <li><a href="{{ route('backend.venues.index') }}">View All</a></li>
            <li><a href="{{ route('backend.venues.create.get') }}">Create New</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-money icon"></i><span>Payments<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Payments</li>
            <li><a href="{{ route('backend.payments.index') }}">View All</a></li>
        </ul>
    </li>
    <li class="heading">Analytics</li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-graduation-cap icon"></i><span>Courses<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Courses</li>
            <li><a href="{{ route('backend.analytics.courses.index') }}">Index</a></li>
            <li><a href="{{ route('backend.analytics.courses.timeline') }}">Timeline</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-calendar icon"></i><span>Events<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Events</li>
            <li><a href="{{ route('backend.analytics.events.index') }}">Index</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-money icon"></i><span>Payments<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Payments</li>
            <li><a href="{{ route('backend.analytics.payments.index') }}">Index</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-file-text icon"></i><span>Registrations<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Registrations</li>
            <li><a href="{{ route('backend.analytics.registrations.index') }}">Index</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-users icon"></i><span>Sales Reps<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Sales Representatives</li>
            <li><a href="{{ route('backend.analytics.sales_representatives.index') }}">Index</a></li>
        </ul>
    </li>
    <li class="heading">System</li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-lock icon"></i><span>Login Attempts<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Analytics</li>
            <li><a href="{{ route('backend.login_attempts.index') }}">View All</a></li>
            <li><a href="{{ route('backend.login_attempts.timeline') }}">Timeline</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-gears icon"></i><span>Settings<b class="caret"></b></span></a>
        <ul class="dropdown-menu">
            <li class="heading">Settings</li>
            <li><a href="{{ route('backend.users.index') }}">Users</a></li>
            <li><a href="{{ route('backend.settings.index') }}">Manage System Settings</a></li>
        </ul>
    </li>
</ul>